[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
# crate-type = ["cdylib", "rlib"]
crate-type = ["lib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"