[package]
name = "fukuoka-ecl-imagetest"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
image = { version = "0.25.2", default-features = false, features = ["png"] }

[lib]
crate-type = ["cdylib", "rlib"]
